{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "08/30/2019", "opponent": " UT Arlington", "result": "L 2-3 ", "attendance": "50"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "08/30/2019", "opponent": " Houston", "result": "W 3-0 ", "attendance": "0"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "08/31/2019", "opponent": " Arizona St.", "result": "L 1-3 ", "attendance": "0"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/04/2019", "opponent": " UTRGV", "result": "L 2-3 ", "attendance": "475"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/06/2019", "opponent": " New Mexico", "result": "W 3-0 ", "attendance": "0"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/06/2019", "opponent": " UTEP", "result": "L 2-3 ", "attendance": "625"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/07/2019", "opponent": " Coppin St.", "result": "W 3-1 ", "attendance": "76"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/12/2019", "opponent": " Southeastern La.", "result": "W 3-2 ", "attendance": "200"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/13/2019", "opponent": " Jackson St.", "result": "W 3-1 ", "attendance": "25"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/14/2019", "opponent": " California Baptist", "result": "W 3-0 ", "attendance": "25"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/17/2019", "opponent": " UTRGV", "result": "W 3-0 ", "attendance": "1,418"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/20/2019", "opponent": " Purdue", "result": "L 0-3 ", "attendance": "0"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/20/2019", "opponent": " Eastern Mich.", "result": "L 0-3 ", "attendance": "0"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/21/2019", "opponent": " Murray St.", "result": "W 3-1 ", "attendance": "50"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/26/2019", "opponent": " SFA", "result": "L 0-3 ", "attendance": "731"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "09/28/2019", "opponent": " Abilene Christian", "result": "L 1-3 ", "attendance": "291"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/03/2019", "opponent": " Northwestern St.", "result": "L 1-3 ", "attendance": "484"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/05/2019", "opponent": " Central Ark.", "result": "W 3-1 ", "attendance": "269"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/08/2019", "opponent": " UIW", "result": "W 3-0 ", "attendance": "402"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/17/2019", "opponent": " Sam Houston St.", "result": "W 3-1 ", "attendance": "450"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/19/2019", "opponent": " Houston Baptist", "result": "W 3-1 ", "attendance": "107"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/24/2019", "opponent": " Nicholls St.", "result": "W 3-2 ", "attendance": "257"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/26/2019", "opponent": " New Orleans", "result": "W 3-0 ", "attendance": "273"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "10/31/2019", "opponent": " McNeese", "result": "W 3-0 ", "attendance": "341"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/02/2019", "opponent": " Lamar University", "result": "W 3-1 ", "attendance": "37"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/07/2019", "opponent": " SFA", "result": "L 2-3 ", "attendance": "575"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/09/2019", "opponent": " Abilene Christian", "result": "W 3-0 ", "attendance": "267"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/14/2019", "opponent": " Northwestern St.", "result": "W 3-0 ", "attendance": "325"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/16/2019", "opponent": " Central Ark.", "result": "L 1-3 ", "attendance": "287"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/22/2019", "opponent": "#5 Central Ark.", "result": "W 3-0 ", "attendance": "329"}
{"teamName": "A&M-Corpus Christi Islanders", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Steve Greene", "date": "11/23/2019", "opponent": "#1 SFA", "result": "L 1-3 ", "attendance": "55"}
{}
{"stat": null, "rank": "Rank", "value": "Value"}
{"stat": "Match W-L Pctg.", "rank": "95", "value": "0.613"}
{"stat": "Hitting Percentage", "rank": "72", "value": "0.233"}
{"stat": "Kills Per Set", "rank": "102", "value": "13.03"}
{"stat": "Assists Per Set", "rank": "92", "value": "12.15"}
{"stat": "Digs Per Set", "rank": "86", "value": "15.64"}
{"stat": "Aces Per Set", "rank": "48", "value": "1.57"}
{"stat": "Blocks Per Set", "rank": "330", "value": "1.14"}
{"stat": "Team Attacks Per Set", "rank": "139", "value": "35.39"}
{"stat": "Opp Hitting Percentage", "rank": "269", "value": "0.227"}
{}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "08/30/2019", "opponent": " Saint Francis (PA)", "result": "W 3-0 ", "attendance": "0"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "08/30/2019", "opponent": " Bucknell", "result": "W 3-1 ", "attendance": "303"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "08/31/2019", "opponent": " The Citadel", "result": "W 3-1 ", "attendance": "298"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/06/2019", "opponent": " Niagara", "result": "W 3-1 ", "attendance": "50"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/06/2019", "opponent": " Cornell", "result": "L 0-3 ", "attendance": "227"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/07/2019", "opponent": " Hartford", "result": "L 0-3 ", "attendance": "50"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/10/2019", "opponent": " Kent St.", "result": "L 2-3 ", "attendance": "403"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/13/2019", "opponent": " Towson", "result": "L 0-3 ", "attendance": "211"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/13/2019", "opponent": " Albany (NY)", "result": "L 0-3 ", "attendance": "89"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/14/2019", "opponent": " Coastal Carolina", "result": "L 1-3 ", "attendance": "31"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/20/2019", "opponent": " Robert Morris", "result": "W 3-0 ", "attendance": "182"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/20/2019", "opponent": " Eastern Ill.", "result": "W 3-1 ", "attendance": "201"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/21/2019", "opponent": " Central Mich.", "result": "L 0-3 ", "attendance": "193"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/27/2019", "opponent": " Northern Ky.", "result": "L 0-3 ", "attendance": "318"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "09/28/2019", "opponent": " Wright St.", "result": "L 0-3 ", "attendance": "265"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/04/2019", "opponent": " UIC", "result": "L 0-3 ", "attendance": "101"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/05/2019", "opponent": " Milwaukee", "result": "L 0-3 ", "attendance": "148"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/09/2019", "opponent": " IUPUI", "result": "W 3-2 ", "attendance": "312"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/11/2019", "opponent": " Green Bay", "result": "L 0-3 ", "attendance": "78"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/18/2019", "opponent": " Cleveland St.", "result": "W 3-1 ", "attendance": "282"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/20/2019", "opponent": " Oakland", "result": "L 0-3 ", "attendance": "137"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/25/2019", "opponent": " Milwaukee", "result": "L 0-3 ", "attendance": "194"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "10/26/2019", "opponent": " UIC", "result": "L 0-3 ", "attendance": "121"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "11/01/2019", "opponent": " Cleveland St.", "result": "L 0-3 ", "attendance": "218"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "11/03/2019", "opponent": " Oakland", "result": "L 0-3 ", "attendance": "518"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "11/06/2019", "opponent": " IUPUI", "result": "L 2-3 ", "attendance": "218"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "11/08/2019", "opponent": " Green Bay", "result": "L 0-3 ", "attendance": "413"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "11/15/2019", "opponent": " Wright St.", "result": "L 0-3 ", "attendance": "168"}
{"teamName": "Youngstown St. Penguins", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Aline Scott", "date": "11/16/2019", "opponent": " Northern Ky.", "result": "L 2-3 ", "attendance": "201"}
{}
{"stat": null, "rank": "Rank", "value": "Value"}
{"stat": "Match W-L Pctg.", "rank": "T-284", "value": "0.276"}
{"stat": "Hitting Percentage", "rank": "315", "value": "0.142"}
{"stat": "Kills Per Set", "rank": "307", "value": "11.04"}
{"stat": "Assists Per Set", "rank": "288", "value": "10.47"}
{"stat": "Digs Per Set", "rank": "67", "value": "15.97"}
{"stat": "Aces Per Set", "rank": "T-131", "value": "1.39"}
{"stat": "Blocks Per Set", "rank": "287", "value": "1.62"}
{"stat": "Team Attacks Per Set", "rank": "81", "value": "36.14"}
{"stat": "Opp Hitting Percentage", "rank": "296", "value": "0.236"}
{}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "Barnes, Carissa", "Yr": "Fr", "Pos": "OH", "Ht": "5-7", "GP": "117", "GS": "", "S": "117", "MP": "", "Attend": "", "Kills": "31", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "8", "Digs": "", "RErr": "", "Block Solos": "2", "Block Assists": "", "BErr": "", "PTS": "29", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "Barnes, Carissa", "Yr": "Fr", "Pos": "OH", "Ht": "5-7", "GP": "117", "GS": "", "S": "117", "MP": "", "Attend": "", "Kills": "31", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "8", "Digs": "", "RErr": "", "Block Solos": "2", "Block Assists": "", "BErr": "", "PTS": "29", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "Fr", "Yr": "5-7", "Pos": "", "Ht": "", "GP": "31", "GS": "", "S": "", "MP": "8", "Attend": "", "Kills": "", "Errors": "29", "Total Attacks": "", "Hit Pct": "", "Assists": "76", "Aces": "", "SErr": "", "Digs": "46", "RErr": "", "Block Solos": "", "Block Assists": "38", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "OH", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "13", "BErr": "L/DS", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "5-7", "Yr": "", "Pos": "", "Ht": "8", "GP": "", "GS": "", "S": "76", "MP": "", "Attend": "", "Kills": "38", "Errors": "", "Total Attacks": "", "Hit Pct": "56.0", "Assists": "", "Aces": "13", "SErr": "5-9", "Digs": "", "RErr": "", "Block Solos": "6", "Block Assists": "", "BErr": "", "PTS": "30", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "117", "Yr": "31", "Pos": "", "Ht": "", "GP": "0.207", "GS": "", "S": "", "MP": "38", "Attend": "", "Kills": "", "Errors": "1", "Total Attacks": "13", "Hit Pct": "117", "Assists": "31", "Aces": "", "SErr": "", "Digs": "0.192", "RErr": "", "Block Solos": "", "Block Assists": "33", "BErr": "", "PTS": "", "BHE": "1", "Trpl Dbl": "14"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "13", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "14", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "117", "Yr": "", "Pos": "", "Ht": "76", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "L/DS", "Kills": "31", "Errors": "", "Total Attacks": "", "Hit Pct": "30", "Assists": "", "Aces": "", "SErr": "36.5", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "46", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "8", "Pos": "", "Ht": "", "GP": "38", "GS": "", "S": "", "MP": "5-9", "Attend": "", "Kills": "", "Errors": "30", "Total Attacks": "", "Hit Pct": "", "Assists": "36.5", "Aces": "14", "SErr": "", "Digs": "196", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "5-9", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "L/DS", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "31", "Yr": "", "Pos": "", "Ht": "38", "GP": "", "GS": "13", "S": "31", "MP": "", "Attend": "", "Kills": "33", "Errors": "", "Total Attacks": "14", "Hit Pct": "31", "Assists": "", "Aces": "", "SErr": "1", "Digs": "", "RErr": "1", "Block Solos": "31", "Block Assists": "", "BErr": "", "PTS": "11", "BHE": "", "Trpl Dbl": "7"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "29", "Pos": "", "Ht": "", "GP": "1", "GS": "", "S": "", "MP": "30", "Attend": "", "Kills": "", "Errors": "Dumity, Sam", "Total Attacks": "", "Hit Pct": "", "Assists": "46", "Aces": "", "SErr": "", "Digs": "116", "RErr": "", "Block Solos": "", "Block Assists": "11", "BErr": "", "PTS": "Jr", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "13", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "14", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "1", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "7", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "56.0", "GP": "117", "GS": "", "S": "30", "MP": "", "Attend": "", "Kills": "31", "Errors": "", "Total Attacks": "", "Hit Pct": "3", "Assists": "So", "Aces": "", "SErr": "21", "Digs": "", "RErr": "", "Block Solos": "115", "Block Assists": "", "BErr": "", "PTS": "18", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "76", "Pos": "", "Ht": "", "GP": "31", "GS": "", "S": "", "MP": "36.5", "Attend": "", "Kills": "", "Errors": "46", "Total Attacks": "", "Hit Pct": "So", "Assists": "238", "Aces": "", "SErr": "", "Digs": "0", "RErr": "", "Block Solos": "", "Block Assists": "44", "BErr": "", "PTS": "", "BHE": "686", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "13", "GP": "", "GS": "", "S": "", "MP": "14", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "1", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "7", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "3", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": "8"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "8", "Yr": "", "Pos": "", "Ht": "5-9", "GP": "", "GS": "", "S": "36.5", "MP": "", "Attend": "", "Kills": "1", "Errors": "", "Total Attacks": "", "Hit Pct": "21", "Assists": "", "Aces": "7", "SErr": "282", "Digs": "", "RErr": "", "Block Solos": "5-8", "Block Assists": "", "BErr": "", "PTS": "325.5", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "46", "Pos": "", "Ht": "", "GP": "0.192", "GS": "", "S": "", "MP": "196", "Attend": "", "Kills": "", "Errors": "116", "Total Attacks": "", "Hit Pct": "", "Assists": "0", "Aces": "", "SErr": "", "Digs": "4", "RErr": "", "Block Solos": "", "Block Assists": "5", "BErr": "", "PTS": "", "BHE": "1", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "1", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "8", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "2", "Yr": "", "Pos": "", "Ht": "6", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "31", "Errors": "", "Total Attacks": "", "Hit Pct": "115", "Assists": "", "Aces": "", "SErr": "5-8", "Digs": "", "RErr": "", "Block Solos": "Young, Rachel", "Block Assists": "", "BErr": "", "PTS": "0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "38", "Pos": "13", "Ht": "", "GP": "33", "GS": "14", "S": "", "MP": "1", "Attend": "1", "Kills": "", "Errors": "11", "Total Attacks": "7", "Hit Pct": "", "Assists": "44", "Aces": "3", "SErr": "", "Digs": "5", "RErr": "8", "Block Solos": "", "Block Assists": "1", "BErr": "6", "PTS": "", "BHE": "", "Trpl Dbl": "17"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "L/DS", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "6", "BErr": "", "PTS": "", "BHE": "MB", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "29", "Yr": "", "Pos": "", "Ht": "30", "GP": "", "GS": "", "S": "46", "MP": "", "Attend": "", "Kills": "11", "Errors": "Jr", "Total Attacks": "", "Hit Pct": "18", "Assists": "", "Aces": "", "SErr": "325.5", "Digs": "", "RErr": "", "Block Solos": "0", "Block Assists": "", "BErr": "", "PTS": "6-5", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "1", "GS": "", "S": "", "MP": "5-9", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "686", "Aces": "", "SErr": "", "Digs": "1", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "MB", "PTS": "", "BHE": "5", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "14", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "7", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "8", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "17", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "0.207", "Yr": "", "Pos": "", "Ht": "33", "GP": "116", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "31", "Errors": "", "Total Attacks": "3", "Hit Pct": "0.284", "Assists": "", "Aces": "", "SErr": "1", "Digs": "85", "RErr": "", "Block Solos": "11", "Block Assists": "", "BErr": "", "PTS": "24", "BHE": "", "Trpl Dbl": "10"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "56.0", "Pos": "", "Ht": "", "GP": "31", "GS": "", "S": "So", "MP": "21", "Attend": "", "Kills": "", "Errors": "18", "Total Attacks": "", "Hit Pct": "", "Assists": "6-1", "Aces": "", "SErr": "", "Digs": "57", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "0", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "OH", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "9", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "76", "Yr": "", "Pos": "", "Ht": "36.5", "GP": "", "GS": "", "S": "238", "MP": "", "Attend": "", "Kills": "44", "Errors": "", "Total Attacks": "", "Hit Pct": "6-1", "Assists": "", "Aces": "6", "SErr": "285", "Digs": "", "RErr": "", "Block Solos": "119.5", "Block Assists": "", "BErr": "", "PTS": "71", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "0", "Pos": "", "Ht": "", "GP": "0.226", "GS": "", "S": "", "MP": "263.0", "Attend": "", "Kills": "", "Errors": "88", "Total Attacks": "", "Hit Pct": "", "Assists": "35", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "6", "BErr": "", "PTS": "", "BHE": "45", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "13", "Pos": "", "Ht": "14", "GP": "", "GS": "1", "S": "", "MP": "7", "Attend": "", "Kills": "3", "Errors": "", "Total Attacks": "8", "Hit Pct": "", "Assists": "6", "Aces": "", "SErr": "17", "Digs": "", "RErr": "9", "Block Solos": "", "Block Assists": "10", "BErr": "", "PTS": "2", "BHE": "", "Trpl Dbl": "21"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "48", "Yr": "So", "Pos": "", "Ht": "6-0", "GP": "", "GS": "", "S": "113", "MP": "", "Attend": "", "Kills": "31", "Errors": "", "Total Attacks": "", "Hit Pct": "9", "Assists": "", "Aces": "", "SErr": "102", "Digs": "", "RErr": "", "Block Solos": "2", "Block Assists": "", "BErr": "", "PTS": "3", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "5-9", "Pos": "", "Ht": "", "GP": "1", "GS": "", "S": "", "MP": "282", "Attend": "", "Kills": "", "Errors": "325.5", "Total Attacks": "", "Hit Pct": "", "Assists": "285", "Aces": "17", "SErr": "", "Digs": "6-1", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "27", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "MB", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "2", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "46", "Yr": "", "Pos": "", "Ht": "196", "GP": "", "GS": "", "S": "0", "MP": "", "Attend": "", "Kills": "5", "Errors": "", "Total Attacks": "", "Hit Pct": "57", "Assists": "", "Aces": "", "SErr": "6-1", "Digs": "", "RErr": "", "Block Solos": "3", "Block Assists": "", "BErr": "", "PTS": "1", "BHE": "So", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "31", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "115", "MP": "44", "Attend": "", "Kills": "", "Errors": "0.340", "Total Attacks": "6", "Hit Pct": "", "Assists": "29", "Aces": "", "SErr": "", "Digs": "1", "RErr": "", "Block Solos": "45", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "0.100", "Trpl Dbl": "11"}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "1", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "8", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "9", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "21", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "A&M-Corpus Christi Islanders", "coach": "Steve Greene", "Jersey": "5", "Player": "590", "Yr": "", "Pos": "", "Ht": "45", "GP": "116", "GS": "", "S": "90", "MP": "", "Attend": "", "Kills": "28", "Errors": "", "Total Attacks": "", "Hit Pct": "Carter, Julia", "Assists": "", "Aces": "", "SErr": "74.5", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "3", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "Hughes, Aleah", "Yr": "Sr", "Pos": "OH", "Ht": "5-9", "GP": "101", "GS": "", "S": "101", "MP": "", "Attend": "", "Kills": "29", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "262", "Digs": "", "RErr": "", "Block Solos": "139", "Block Assists": "", "BErr": "", "PTS": "873", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "Hughes, Aleah", "Yr": "Sr", "Pos": "OH", "Ht": "5-9", "GP": "101", "GS": "", "S": "101", "MP": "", "Attend": "", "Kills": "29", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "262", "Digs": "", "RErr": "", "Block Solos": "139", "Block Assists": "", "BErr": "", "PTS": "873", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "Sr", "Yr": "5-9", "Pos": "", "Ht": "", "GP": "29", "GS": "", "S": "", "MP": "262", "Attend": "", "Kills": "", "Errors": "873", "Total Attacks": "", "Hit Pct": "", "Assists": "32", "Aces": "", "SErr": "", "Digs": "50", "RErr": "", "Block Solos": "", "Block Assists": "20", "BErr": "", "PTS": "", "BHE": "20", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "OH", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "12", "BErr": "OH", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "5-9", "Yr": "", "Pos": "", "Ht": "262", "GP": "", "GS": "", "S": "32", "MP": "", "Attend": "", "Kills": "20", "Errors": "", "Total Attacks": "", "Hit Pct": "299.0", "Assists": "", "Aces": "12", "SErr": "5-11", "Digs": "", "RErr": "", "Block Solos": "77", "Block Assists": "", "BErr": "", "PTS": "52", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "101", "Yr": "29", "Pos": "", "Ht": "", "GP": "0.141", "GS": "", "S": "", "MP": "20", "Attend": "", "Kills": "", "Errors": "2", "Total Attacks": "12", "Hit Pct": "101", "Assists": "29", "Aces": "", "SErr": "", "Digs": "0.109", "RErr": "", "Block Solos": "", "Block Assists": "27", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": "14"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "12", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "14", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "101", "Yr": "", "Pos": "", "Ht": "32", "GP": "", "GS": "", "S": "4", "MP": "", "Attend": "OH", "Kills": "29", "Errors": "", "Total Attacks": "", "Hit Pct": "13", "Assists": "", "Aces": "", "SErr": "95.5", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "10", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "262", "Pos": "", "Ht": "", "GP": "20", "GS": "", "S": "", "MP": "5-11", "Attend": "", "Kills": "", "Errors": "52", "Total Attacks": "", "Hit Pct": "", "Assists": "95.5", "Aces": "14", "SErr": "", "Digs": "110", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "5-10", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "OH", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "10", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "29", "Yr": "", "Pos": "", "Ht": "20", "GP": "", "GS": "12", "S": "29", "MP": "", "Attend": "", "Kills": "27", "Errors": "", "Total Attacks": "14", "Hit Pct": "29", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "10", "Block Solos": "29", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": "15"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "873", "Pos": "", "Ht": "", "GP": "2", "GS": "", "S": "", "MP": "52", "Attend": "", "Kills": "", "Errors": "Beaupre, Aimee", "Total Attacks": "", "Hit Pct": "", "Assists": "10", "Aces": "", "SErr": "", "Digs": "92", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "So", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "12", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "14", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "10", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "15", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "299.0", "GP": "101", "GS": "", "S": "13", "MP": "", "Attend": "", "Kills": "29", "Errors": "", "Total Attacks": "", "Hit Pct": "12", "Assists": "Sr", "Aces": "", "SErr": "5", "Digs": "", "RErr": "", "Block Solos": "86", "Block Assists": "", "BErr": "", "PTS": "42", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "32", "Pos": "", "Ht": "", "GP": "29", "GS": "", "S": "", "MP": "95.5", "Attend": "", "Kills": "", "Errors": "10", "Total Attacks": "", "Hit Pct": "Sr", "Assists": "117", "Aces": "", "SErr": "", "Digs": "0", "RErr": "", "Block Solos": "", "Block Assists": "10", "BErr": "", "PTS": "", "BHE": "321", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "12", "GP": "", "GS": "", "S": "", "MP": "14", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "10", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "15", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "23", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": "11"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "262", "Yr": "", "Pos": "", "Ht": "5-11", "GP": "", "GS": "", "S": "95.5", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "5", "Assists": "", "Aces": "15", "SErr": "249", "Digs": "", "RErr": "", "Block Solos": "5-10", "Block Assists": "", "BErr": "", "PTS": "131.0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "50", "Pos": "", "Ht": "", "GP": "0.109", "GS": "", "S": "", "MP": "110", "Attend": "", "Kills": "", "Errors": "92", "Total Attacks": "", "Hit Pct": "", "Assists": "0", "Aces": "", "SErr": "", "Digs": "5", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "11", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "10", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "11", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "139", "Yr": "", "Pos": "", "Ht": "77", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "29", "Errors": "", "Total Attacks": "", "Hit Pct": "86", "Assists": "", "Aces": "", "SErr": "5-10", "Digs": "", "RErr": "", "Block Solos": "Seagroves, Reilly", "Block Assists": "", "BErr": "", "PTS": "0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "20", "Pos": "12", "Ht": "", "GP": "27", "GS": "14", "S": "", "MP": "", "Attend": "10", "Kills": "", "Errors": "", "Total Attacks": "15", "Hit Pct": "", "Assists": "10", "Aces": "23", "SErr": "", "Digs": "", "RErr": "11", "Block Solos": "", "Block Assists": "24", "BErr": "9", "PTS": "", "BHE": "", "Trpl Dbl": "2"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "OH", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "9", "BErr": "", "PTS": "", "BHE": "MB", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "873", "Yr": "", "Pos": "", "Ht": "52", "GP": "", "GS": "", "S": "10", "MP": "", "Attend": "", "Kills": "", "Errors": "So", "Total Attacks": "", "Hit Pct": "42", "Assists": "", "Aces": "", "SErr": "131.0", "Digs": "", "RErr": "", "Block Solos": "0", "Block Assists": "", "BErr": "", "PTS": "5-11", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "20", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "5-10", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "321", "Aces": "", "SErr": "", "Digs": "11", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "MB", "PTS": "", "BHE": "2", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "14", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "15", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "11", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "2", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "0.141", "Yr": "", "Pos": "", "Ht": "27", "GP": "96", "GS": "", "S": "1", "MP": "", "Attend": "", "Kills": "25", "Errors": "", "Total Attacks": "23", "Hit Pct": "0.184", "Assists": "", "Aces": "", "SErr": "24", "Digs": "64", "RErr": "", "Block Solos": "23", "Block Assists": "", "BErr": "", "PTS": "16", "BHE": "", "Trpl Dbl": "13"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "299.0", "Pos": "", "Ht": "", "GP": "29", "GS": "", "S": "Sr", "MP": "5", "Attend": "", "Kills": "", "Errors": "42", "Total Attacks": "", "Hit Pct": "", "Assists": "5-3", "Aces": "", "SErr": "", "Digs": "42", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "0", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "RS", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "20", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "32", "Yr": "", "Pos": "", "Ht": "95.5", "GP": "", "GS": "", "S": "117", "MP": "", "Attend": "", "Kills": "10", "Errors": "", "Total Attacks": "", "Hit Pct": "5-3", "Assists": "", "Aces": "9", "SErr": "261", "Digs": "", "RErr": "", "Block Solos": "95.0", "Block Assists": "", "BErr": "", "PTS": "1", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "0", "Pos": "", "Ht": "", "GP": "0.121", "GS": "", "S": "", "MP": "188.5", "Attend": "", "Kills": "", "Errors": "42", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "8", "BErr": "", "PTS": "", "BHE": "19", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "12", "Pos": "", "Ht": "14", "GP": "", "GS": "10", "S": "", "MP": "15", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "11", "Hit Pct": "", "Assists": "9", "Aces": "", "SErr": "2", "Digs": "", "RErr": "20", "Block Solos": "", "Block Assists": "13", "BErr": "", "PTS": "3", "BHE": "", "Trpl Dbl": "1"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "25", "Yr": "Jr", "Pos": "", "Ht": "6-0", "GP": "", "GS": "", "S": "56", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "73", "Digs": "", "RErr": "", "Block Solos": "6", "Block Assists": "", "BErr": "", "PTS": "45", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "5-11", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "249", "Attend": "", "Kills": "", "Errors": "131.0", "Total Attacks": "", "Hit Pct": "", "Assists": "261", "Aces": "2", "SErr": "", "Digs": "5-10", "RErr": "", "Block Solos": "", "Block Assists": "14", "BErr": "", "PTS": "", "BHE": "1", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "DS", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "3", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "50", "Yr": "", "Pos": "", "Ht": "110", "GP": "", "GS": "", "S": "0", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "42", "Assists": "", "Aces": "", "SErr": "5-10", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "4", "BHE": "Fr", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "29", "Pos": "", "Ht": "", "GP": "1", "GS": "", "S": "86", "MP": "10", "Attend": "", "Kills": "", "Errors": "-0.167", "Total Attacks": "9", "Hit Pct": "", "Assists": "20", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "19", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "0.000", "Trpl Dbl": "4"}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "10", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "11", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "20", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "323", "Yr": "", "Pos": "", "Ht": "4", "GP": "92", "GS": "", "S": "114", "MP": "", "Attend": "", "Kills": "26", "Errors": "", "Total Attacks": "", "Hit Pct": "Haggerty, Valor", "Assists": "", "Aces": "", "SErr": "95.5", "Digs": "", "RErr": "", "Block Solos": "1", "Block Assists": "", "BErr": "", "PTS": "2", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "77", "Pos": "", "Ht": "", "GP": "29", "GS": "", "S": "", "MP": "5-10", "Attend": "", "Kills": "", "Errors": "0", "Total Attacks": "", "Hit Pct": "", "Assists": "95.0", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "So", "Block Assists": "11", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Youngstown St. Penguins", "coach": "Aline Scott", "Jersey": "5", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "RS", "RErr": "", "Block Solos": "", "Block Assists": "6", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/06/2019", "opponent": " Oklahoma", "result": "L 2-3 ", "attendance": "213"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/06/2019", "opponent": " Oregon St.", "result": "L 1-3 ", "attendance": "0"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/08/2019", "opponent": " Indiana", "result": "L 1-3 ", "attendance": "1,432"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/13/2019", "opponent": " Villanova", "result": "L 1-3 ", "attendance": "110"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/13/2019", "opponent": " Southern California", "result": "L 2-3 ", "attendance": "975"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/14/2019", "opponent": " Howard", "result": "W 3-0 ", "attendance": "200"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/20/2019", "opponent": " Stony Brook", "result": "W 3-0 ", "attendance": "315"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/21/2019", "opponent": " Army West Point", "result": "W 3-0 ", "attendance": "226"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/21/2019", "opponent": " Sacred Heart", "result": "W 3-0 ", "attendance": "411"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "09/28/2019", "opponent": " Brown", "result": "W 3-0 ", "attendance": "462"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/04/2019", "opponent": " Harvard", "result": "W 3-0 ", "attendance": "688"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/05/2019", "opponent": " Dartmouth", "result": "W 3-1 ", "attendance": "702"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/12/2019", "opponent": " Penn", "result": "W 3-0 ", "attendance": "331"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/13/2019", "opponent": " Princeton", "result": "L 0-3 ", "attendance": "276"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/18/2019", "opponent": " Columbia", "result": "W 3-0 ", "attendance": "521"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/19/2019", "opponent": " Cornell", "result": "W 3-1 ", "attendance": "316"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "10/26/2019", "opponent": " Brown", "result": "W 3-0 ", "attendance": "212"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "11/01/2019", "opponent": " Dartmouth", "result": "W 3-0 ", "attendance": "158"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "11/02/2019", "opponent": " Harvard", "result": "L 1-3 ", "attendance": "375"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "11/08/2019", "opponent": " Cornell", "result": "W 3-1 ", "attendance": "298"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "11/09/2019", "opponent": " Columbia", "result": "W 3-0 ", "attendance": "194"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "11/16/2019", "opponent": " Princeton", "result": "W 3-2 ", "attendance": "816"}
{"teamName": "Yale Bulldogs", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Erin Appleman", "date": "11/22/2019", "opponent": " Princeton", "result": "L 1-3 ", "attendance": "737"}
{}
{"stat": null, "rank": "Rank", "value": "Value"}
{"stat": "Match W-L Pctg.", "rank": "76", "value": "0.652"}
{"stat": "Hitting Percentage", "rank": "50", "value": "0.244"}
{"stat": "Kills Per Set", "rank": "82", "value": "13.23"}
{"stat": "Assists Per Set", "rank": "118", "value": "11.93"}
{"stat": "Digs Per Set", "rank": "193", "value": "14.40"}
{"stat": "Aces Per Set", "rank": "123", "value": "1.40"}
{"stat": "Blocks Per Set", "rank": "263", "value": "1.73"}
{"stat": "Team Attacks Per Set", "rank": "180", "value": "34.94"}
{"stat": "Opp Hitting Percentage", "rank": "228", "value": "0.219"}
{}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "08/30/2019", "opponent": " Southern Utah", "result": "L 0-3 ", "attendance": "0"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "08/30/2019", "opponent": " Utah St.", "result": "W 3-1 ", "attendance": "406"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "08/31/2019", "opponent": " Eastern Mich.", "result": "W 3-1 ", "attendance": "0"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/06/2019", "opponent": " Akron", "result": "L 2-3 ", "attendance": "0"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/07/2019", "opponent": " William & Mary", "result": "W 3-1 ", "attendance": "0"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/07/2019", "opponent": " Wright St.", "result": "L 0-3 ", "attendance": "0"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/13/2019", "opponent": " Lipscomb", "result": "L 1-3 ", "attendance": "417"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/14/2019", "opponent": " Louisville", "result": "L 0-3 ", "attendance": "115"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/19/2019", "opponent": " Cincinnati", "result": "L 0-3 ", "attendance": "1,308"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/20/2019", "opponent": " Bowling Green", "result": "L 1-3 ", "attendance": "579"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "09/25/2019", "opponent": " DePaul", "result": "W 3-2 ", "attendance": "0"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/02/2019", "opponent": " Marquette", "result": "L 1-3 ", "attendance": "209"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/04/2019", "opponent": " Villanova", "result": "L 0-3 ", "attendance": "317"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/05/2019", "opponent": " Georgetown", "result": "W 3-2 ", "attendance": "188"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/11/2019", "opponent": " Seton Hall", "result": "W 3-0 ", "attendance": "312"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/12/2019", "opponent": " St. John's (NY)", "result": "L 0-3 ", "attendance": "422"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/18/2019", "opponent": " Providence", "result": "W 3-1 ", "attendance": "137"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/20/2019", "opponent": " Creighton", "result": "L 0-3 ", "attendance": "1,918"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/25/2019", "opponent": " Georgetown", "result": "W 3-2 ", "attendance": "604"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "10/26/2019", "opponent": " Villanova", "result": "L 0-3 ", "attendance": "523"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/01/2019", "opponent": " Marquette", "result": "L 0-3 ", "attendance": "740"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/03/2019", "opponent": " DePaul", "result": "W 3-1 ", "attendance": "672"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/09/2019", "opponent": " St. John's (NY)", "result": "L 0-3 ", "attendance": "125"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/09/2019", "opponent": " Seton Hall", "result": "W 3-2 ", "attendance": "353"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/16/2019", "opponent": " Creighton", "result": "L 0-3 ", "attendance": "712"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/17/2019", "opponent": " Providence", "result": "W 3-1 ", "attendance": "326"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/22/2019", "opponent": " Butler", "result": "L 0-3 ", "attendance": "670"}
{"teamName": "Xavier Musketeers", "season": "2019-20", "sport": "Women's Volleyball", "headCoach": "Christy Pfeffenberger", "date": "11/23/2019", "opponent": " Butler", "result": "L 0-3 ", "attendance": "524"}
{}
{"stat": null, "rank": "Rank", "value": "Value"}
{"stat": "Match W-L Pctg.", "rank": "T-233", "value": "0.393"}
{"stat": "Hitting Percentage", "rank": "203", "value": "0.194"}
{"stat": "Kills Per Set", "rank": "222", "value": "12.08"}
{"stat": "Assists Per Set", "rank": "208", "value": "11.32"}
{"stat": "Digs Per Set", "rank": "107", "value": "15.37"}
{"stat": "Aces Per Set", "rank": "329", "value": "0.91"}
{"stat": "Blocks Per Set", "rank": "75", "value": "2.31"}
{"stat": "Team Attacks Per Set", "rank": "109", "value": "35.74"}
{"stat": "Opp Hitting Percentage", "rank": "285", "value": "0.233"}
{}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "DeJardin, Ellis", "Yr": "So", "Pos": "OH", "Ht": "5-9", "GP": "83", "GS": "", "S": "83", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "202", "Digs": "", "RErr": "", "Block Solos": "81", "Block Assists": "", "BErr": "", "PTS": "734", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "DeJardin, Ellis", "Yr": "So", "Pos": "OH", "Ht": "5-9", "GP": "83", "GS": "", "S": "83", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "202", "Digs": "", "RErr": "", "Block Solos": "81", "Block Assists": "", "BErr": "", "PTS": "734", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "So", "Yr": "5-9", "Pos": "", "Ht": "", "GP": "23", "GS": "", "S": "", "MP": "202", "Attend": "", "Kills": "", "Errors": "734", "Total Attacks": "", "Hit Pct": "", "Assists": "17", "Aces": "", "SErr": "", "Digs": "10", "RErr": "", "Block Solos": "", "Block Assists": "19", "BErr": "", "PTS": "", "BHE": "23", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "OH", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "23", "BErr": "S", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "5-9", "Yr": "", "Pos": "", "Ht": "202", "GP": "", "GS": "", "S": "17", "MP": "", "Attend": "", "Kills": "19", "Errors": "", "Total Attacks": "", "Hit Pct": "243.5", "Assists": "", "Aces": "23", "SErr": "5-11", "Digs": "", "RErr": "", "Block Solos": "75", "Block Assists": "", "BErr": "", "PTS": "831", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "83", "Yr": "23", "Pos": "", "Ht": "", "GP": "0.165", "GS": "", "S": "", "MP": "19", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "23", "Hit Pct": "83", "Assists": "23", "Aces": "", "SErr": "", "Digs": "0.302", "RErr": "", "Block Solos": "", "Block Assists": "3", "BErr": "", "PTS": "", "BHE": "5", "Trpl Dbl": "16"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "16", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "83", "Yr": "", "Pos": "", "Ht": "17", "GP": "", "GS": "", "S": "5", "MP": "", "Attend": "S", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "21", "Assists": "", "Aces": "", "SErr": "115.0", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "13", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "202", "Pos": "", "Ht": "", "GP": "19", "GS": "", "S": "", "MP": "5-11", "Attend": "", "Kills": "", "Errors": "831", "Total Attacks": "", "Hit Pct": "", "Assists": "115.0", "Aces": "16", "SErr": "", "Digs": "0", "RErr": "", "Block Solos": "", "Block Assists": "21", "BErr": "", "PTS": "", "BHE": "6-0", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "S", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "23", "Yr": "", "Pos": "", "Ht": "19", "GP": "", "GS": "23", "S": "23", "MP": "", "Attend": "", "Kills": "3", "Errors": "", "Total Attacks": "16", "Hit Pct": "23", "Assists": "", "Aces": "", "SErr": "21", "Digs": "", "RErr": "1", "Block Solos": "23", "Block Assists": "", "BErr": "", "PTS": "19", "BHE": "", "Trpl Dbl": "2"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "734", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "831", "Attend": "", "Kills": "", "Errors": "Boyd, Yurika", "Total Attacks": "", "Hit Pct": "", "Assists": "13", "Aces": "", "SErr": "", "Digs": "83", "RErr": "", "Block Solos": "", "Block Assists": "19", "BErr": "", "PTS": "Sr", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "23", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "16", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "1", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "2", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "243.5", "GP": "83", "GS": "", "S": "21", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "Jr", "Aces": "", "SErr": "26", "Digs": "", "RErr": "", "Block Solos": "83", "Block Assists": "", "BErr": "", "PTS": "49", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "17", "Pos": "", "Ht": "", "GP": "23", "GS": "", "S": "", "MP": "115.0", "Attend": "", "Kills": "", "Errors": "13", "Total Attacks": "", "Hit Pct": "Jr", "Assists": "205", "Aces": "", "SErr": "", "Digs": "0", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "7", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "23", "GP": "", "GS": "", "S": "", "MP": "16", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "1", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "2", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "9", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": "15"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "202", "Yr": "", "Pos": "", "Ht": "5-11", "GP": "", "GS": "", "S": "115.0", "MP": "", "Attend": "", "Kills": "21", "Errors": "", "Total Attacks": "", "Hit Pct": "26", "Assists": "", "Aces": "2", "SErr": "181", "Digs": "", "RErr": "", "Block Solos": "5-9", "Block Assists": "", "BErr": "", "PTS": "25.0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "10", "Pos": "", "Ht": "", "GP": "0.302", "GS": "", "S": "", "MP": "0", "Attend": "", "Kills": "", "Errors": "83", "Total Attacks": "", "Hit Pct": "", "Assists": "0", "Aces": "", "SErr": "", "Digs": "5", "RErr": "", "Block Solos": "", "Block Assists": "19", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "1", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "15", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "81", "Yr": "", "Pos": "", "Ht": "75", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "83", "Assists": "", "Aces": "", "SErr": "5-9", "Digs": "", "RErr": "", "Block Solos": "Bray, Samantha", "Block Assists": "", "BErr": "", "PTS": "0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "19", "Pos": "23", "Ht": "", "GP": "3", "GS": "16", "S": "", "MP": "21", "Attend": "1", "Kills": "", "Errors": "19", "Total Attacks": "2", "Hit Pct": "", "Assists": "", "Aces": "9", "SErr": "", "Digs": "19", "RErr": "15", "Block Solos": "", "Block Assists": "", "BErr": "17", "PTS": "", "BHE": "", "Trpl Dbl": "12"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "S", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "17", "BErr": "", "PTS": "", "BHE": "RS", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "734", "Yr": "", "Pos": "", "Ht": "831", "GP": "", "GS": "", "S": "13", "MP": "", "Attend": "", "Kills": "19", "Errors": "Sr", "Total Attacks": "", "Hit Pct": "49", "Assists": "", "Aces": "", "SErr": "25.0", "Digs": "", "RErr": "", "Block Solos": "0", "Block Assists": "", "BErr": "", "PTS": "6-0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "23", "Pos": "", "Ht": "", "GP": "5", "GS": "", "S": "", "MP": "6-0", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "7", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "RS", "PTS": "", "BHE": "3", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "16", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "2", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "15", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "12", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "0.165", "Yr": "", "Pos": "", "Ht": "3", "GP": "83", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "9", "Hit Pct": "0.286", "Assists": "", "Aces": "", "SErr": "", "Digs": "67", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "18", "BHE": "", "Trpl Dbl": "18"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "243.5", "Pos": "", "Ht": "", "GP": "23", "GS": "", "S": "Jr", "MP": "26", "Attend": "", "Kills": "", "Errors": "49", "Total Attacks": "", "Hit Pct": "", "Assists": "5-11", "Aces": "", "SErr": "", "Digs": "5", "RErr": "", "Block Solos": "", "Block Assists": "1", "BErr": "", "PTS": "", "BHE": "0", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "MB", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "10", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "17", "Yr": "", "Pos": "", "Ht": "115.0", "GP": "", "GS": "", "S": "205", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "5-11", "Assists": "", "Aces": "17", "SErr": "32", "Digs": "", "RErr": "", "Block Solos": "168.0", "Block Assists": "", "BErr": "", "PTS": "38", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "0", "Pos": "", "Ht": "", "GP": "-0.143", "GS": "", "S": "", "MP": "232.0", "Attend": "", "Kills": "", "Errors": "1", "Total Attacks": "", "Hit Pct": "", "Assists": "45", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "12", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "23", "Pos": "", "Ht": "16", "GP": "", "GS": "1", "S": "", "MP": "2", "Attend": "", "Kills": "9", "Errors": "", "Total Attacks": "15", "Hit Pct": "", "Assists": "17", "Aces": "", "SErr": "12", "Digs": "", "RErr": "10", "Block Solos": "", "Block Assists": "18", "BErr": "", "PTS": "3", "BHE": "", "Trpl Dbl": "4"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "18", "Yr": "Sr", "Pos": "", "Ht": "5-6", "GP": "", "GS": "", "S": "189", "MP": "", "Attend": "", "Kills": "23", "Errors": "", "Total Attacks": "", "Hit Pct": "8", "Assists": "", "Aces": "", "SErr": "157", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "0", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "5-11", "Pos": "", "Ht": "", "GP": "21", "GS": "", "S": "", "MP": "181", "Attend": "", "Kills": "", "Errors": "25.0", "Total Attacks": "", "Hit Pct": "", "Assists": "32", "Aces": "12", "SErr": "", "Digs": "6-1", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "5", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "MB", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "3", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "10", "Yr": "", "Pos": "", "Ht": "0", "GP": "", "GS": "", "S": "0", "MP": "", "Attend": "", "Kills": "19", "Errors": "", "Total Attacks": "", "Hit Pct": "5", "Assists": "", "Aces": "", "SErr": "6-1", "Digs": "", "RErr": "", "Block Solos": "9", "Block Assists": "", "BErr": "", "PTS": "1", "BHE": "Jr", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "23", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "83", "MP": "", "Attend": "", "Kills": "", "Errors": "0.370", "Total Attacks": "17", "Hit Pct": "", "Assists": "17", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "12", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "-0.111", "Trpl Dbl": "5"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "1", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "15", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "10", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "4", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "218", "Yr": "", "Pos": "", "Ht": "60", "GP": "83", "GS": "", "S": "60", "MP": "", "Attend": "", "Kills": "22", "Errors": "", "Total Attacks": "", "Hit Pct": "Nemeth, Rebekah", "Assists": "", "Aces": "", "SErr": "33.0", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "1", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "75", "Pos": "", "Ht": "", "GP": "23", "GS": "", "S": "", "MP": "5-9", "Attend": "", "Kills": "", "Errors": "0", "Total Attacks": "", "Hit Pct": "", "Assists": "168.0", "Aces": "", "SErr": "", "Digs": "9", "RErr": "", "Block Solos": "Fr", "Block Assists": "", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "OH", "RErr": "", "Block Solos": "", "Block Assists": "8", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "19", "Yr": "", "Pos": "16", "Ht": "21", "GP": "", "GS": "2", "S": "", "MP": "", "Attend": "15", "Kills": "", "Errors": "", "Total Attacks": "12", "Hit Pct": "1", "Assists": "", "Aces": "18", "SErr": "", "Digs": "", "RErr": "4", "Block Solos": "", "Block Assists": "", "BErr": "5", "PTS": "", "BHE": "", "Trpl Dbl": "6"}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "182", "Pos": "L", "Ht": "", "GP": "0.214", "GS": "", "S": "", "MP": "12", "Attend": "", "Kills": "", "Errors": "15", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "4", "RErr": "", "Block Solos": "", "Block Assists": "", "BErr": "", "PTS": "Jr", "BHE": "", "Trpl Dbl": ""}
{"year": "2019-20", "team": "Yale Bulldogs", "coach": "Erin Appleman", "Jersey": "55", "Player": "", "Yr": "", "Pos": "", "Ht": "", "GP": "", "GS": "", "S": "", "MP": "", "Attend": "", "Kills": "17", "Errors": "", "Total Attacks": "", "Hit Pct": "", "Assists": "", "Aces": "", "SErr": "", "Digs": "", "RErr": "", "Block Solos": "", "Block Assists": "5", "BErr": "", "PTS": "", "BHE": "", "Trpl Dbl": ""}
